<div id="docSettingsDialog" title="Document Settings">
	<form name="docSettings">
		<label for="lineNumbers">Line Numbers: </label>
		<select name="lineNumbers">
			<option value="show" selected>Show</value>
			<option value="hide">Hide</value>
		</select><br />

		<label for="pageNumbers">Page Numbers: </label>
		<select name="pageNumbers">
			<option value="hide" selected>Hide</value>
		</select><br />

		<label for="surplusBlocks">Scribal Additions: </label>
		<select name="surplusBlocks">
			<option value="show" selected>Show</value>
			<option value="hide">Hide</value>
		</select><br />

		<label for="linkIDs">Link IDs: </label>
		<select name="linkIDs">
			<option value="show">Show</value>
			<option value="hide" selected>Hide</value>
		</select><br />
	</form>
</div>