<div id="settingsDialog" title="Settings">
	<form name="settings">
		<label for="apparatusStyle">Display Apparatus: </label>
		<select name="apparatusStyle">
			<option value="inline">Inline with the text</value>
			<option value="footer">In the footer when highlighted</value>
			<option value="popUp" selected>As pop-up links</value>
			<option value="hidden">Hidden</value>
		</select><br />

		<label for="generalNoteStyle">Display Notes: </label>
		<select name="generalNoteStyle">
			<option value="inline">Inline with the text</value>
			<option value="footer">In the footer when highlighted</value>
			<option value="popUp" selected>As pop-up links</value>
			<option value="hidden">Hidden</value>
		</select><br />

		<label for="commentaryNoteStyle">Display Commentary Notes: </label>
		<select name="commentaryNoteStyle">
			<option value="inline">Inline with the text</value>
			<option value="footer">In the footer when highlighted</value>
			<option value="popUp" selected>As pop-up links</value>
			<option value="hidden">Hidden</value>
		</select><br />

		<label for="sourceNoteStyle">Display Source Notes: </label>
		<select name="sourceNoteStyle">
			<option value="inline" selected>Inline with the text</value>
			<option value="footer">In the footer when highlighted</value>
			<option value="popUp">As pop-up links</value>
			<option value="hidden">Hidden</value>
		</select><br />

		<label for="apparatusNoteStyle">Display Apparatus Notes: </label>
		<select name="apparatusNoteStyle">
			<option value="inline">Inline with the text</value>
			<option value="footer">In the footer when highlighted</value>
			<option value="popUp">As pop-up links</value>
			<option value="hidden" selected>Hidden</value>
		</select><br />

		<label for="hoverBehaviour">Hover Behaviour: </label>
		<select name="hoverBehaviour">
			<option value="none">Do nothing</value>
			<option value="highlight">Highlight only</value>
			<option value="getRelated" selected>Highlight and mark related</value>
		</select><br />

		<label for="hoverPopups">Hover Popups: </label>
		<select name="hoverPopups">
				<option value="show" selected>Show</value>
				<option value="hide">Hide</value>
		</select><br />

		<label for="awldPopups"><a href="http://isawnyu.github.io/awld-js/" class="awld-scope">AWLD</a> popups: </label>
		<select name="awldPopups">
				<option value="show" selected>Show</value>
				<option value="hide">Hide</value>
		</select><br />
	</form>
</div>
